export const languages = [
  { value: 'JavaScript', color: '#F7DF1E', icon: '🟨' },
  { value: 'Python', color: '#3776AB', icon: '🐍' },
  { value: 'Java', color: '#ED8B00', icon: '☕' },
  { value: 'C++', color: '#00599C', icon: '⚙️' },
  { value: 'C#', color: '#239120', icon: '💜' },
  { value: 'HTML', color: '#E34F26', icon: '🌐' },
  { value: 'CSS', color: '#1572B6', icon: '🎨' },
  { value: 'React', color: '#61DAFB', icon: '⚛️' },
  { value: 'Node.js', color: '#339933', icon: '🟢' },
  { value: 'TypeScript', color: '#3178C6', icon: '📘' },
  { value: 'Go', color: '#00ADD8', icon: '🐹' },
  { value: 'Rust', color: '#000000', icon: '🦀' },
  { value: 'PHP', color: '#777BB4', icon: '🐘' },
  { value: 'Ruby', color: '#CC342D', icon: '💎' },
  { value: 'Swift', color: '#FA7343', icon: '🐦' },
  { value: 'Kotlin', color: '#7F52FF', icon: '🅺' },
  { value: 'SQL', color: '#336791', icon: '🗃️' },
  { value: 'MongoDB', color: '#47A248', icon: '🍃' },
  { value: 'Docker', color: '#2496ED', icon: '🐳' },
  { value: 'Shell', color: '#4EAA25', icon: '💻' },
  { value: 'JSON', color: '#000000', icon: '📋' },
  { value: 'XML', color: '#005CE6', icon: '📄' },
  { value: 'YAML', color: '#CB171E', icon: '📝' },
  { value: 'Other', color: '#6C757D', icon: '📄' },
];